### ISSUE TITLE
How use with --modern flag?

### ISSUE THREAD

**Issue by yarkovaleksei** [cheap-glitch/vue-cli-plugin-sitemap#21]
If I build the application with the --modern flag, then the error appears:
```
out:  ERROR  Error: Command failed: node /usr/src/app/node_modules/@vue/cli-service/bin/vue-cli-service.js build --modern --silent
out: Error: Command failed: node /usr/src/app/node_modules/@vue/cli-service/bin/vue-cli-service.js build --modern --silent
out:     at makeError (/usr/src/app/node_modules/execa/index.js:174:9)
out:     at /usr/src/app/node_modules/execa/index.js:278:16
out:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
out:     at async /usr/src/app/node_modules/@vue/cli-service/lib/commands/build/index.js:66:9
out:     at async build.fn (/usr/src/app/node_modules/vue-cli-plugin-sitemap/index.js:69:4)
```

**Comment by cheap-glitch** [comment]
I tried running `npm run build -- --modern --silent` in a fresh project scaffolded with Vue CLI, and it works fine.

There's a good chance the error might come from your own config — feel free to post it here if you'd like some help debugging it.
