### ISSUE TITLE
null pointer during dynamic route without children

### ISSUE THREAD

**Issue by steven87vt** [cheap-glitch/vue-cli-plugin-sitemap#30]
I think theres a problem with the way the `generateURLsFromRoutes` function handles children. In the case of dynamic routes, its acceptable not to have children routes defined and this function checks for `children in route`. However, the validation setup in the plugin startup process assigns children to undefined if they are not defined at all.

So eventually the `generateURLsFromRoute` function tries to recurse for child routes and you get a `undefined while reading .map` 

```js
async function generateURLsFromRoutes(routes, parentPath = '', parentMeta = {}) {
  const urls = await Promise.all(routes.map(async function(route) {
  // Avoid "contaminating" children route with parent 'loc' property
  delete parentMeta.loc;
  ......

  /**
  * Static route
  */
  // this causes the undefined reference from the above Promise.all(routes.map)
  if (!params.length) return ('children' in route) ? await generateURLsFromRoutes(route.children, path,     meta) : { loc: path, ...meta };
```

Here is the raw route definition:

```json
{
   "path": "/policies/:type(terms\\-of\\-service|privacy\\-policy)",
   "name": "policyView",
   "components": { "default": "PolicyView", "NavBar": "NavBar" },
   "meta": {
     "sitemap": {
       "slugs": [
         {
           "type": "privacy-policy",
           "priority": 1.0
         },
         {
           "type": "terms-of-service",,
           "priority": 1.0
         }
       ]
     }
   }
}
```

The rational here is, all I want to do is swap some component logic in the same parent route:
`/policies/privacy-policy` -> matches `policyView` -> renders cached PolicyView component; async loaded & webpack chunked
`/policies/terms-of-service` -> matches `policyView` -> renders cached PolicyView component; async loaded & webpack chunked

The component simply swaps the `vuex` reference for the text content based on the matched route `param: { type: 'privacy-policy or terms-of-service' }` value.

Here is the stack trace:

```ps
ERROR  TypeError: Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at generateURLsFromRoutes (/home/ezwebproductions/workspaces/web/sites/ezwebproductions/node_modules/vue-cli-plugin-sitemap/src/sitemap.js:99:40)
    at /home/ezwebproductions/workspaces/web/sites/ezwebproductions/node_modules/vue-cli-plugin-sitemap/src/sitemap.js:121:60
    at Array.map (<anonymous>)
    at generateURLsFromRoutes (/home/ezwebproductions/workspaces/web/sites/ezwebproductions/node_modules/vue-cli-plugin-sitemap/src/sitemap.js:99:40)
    at generateSitemaps (/home/ezwebproductions/workspaces/web/sites/ezwebproductions/node_modules/vue-cli-plugin-sitemap/src/sitemap.js:14:100)
    at writeSitemap (/home/ezwebproductions/workspaces/web/sites/ezwebproductions/node_modules/vue-cli-plugin-sitemap/index.js:84:25)
    at build.fn (/home/ezwebproductions/workspaces/web/sites/ezwebproductions/node_modules/vue-cli-plugin-sitemap/index.js:74:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

After setting the null checks in the 3 locations I saw within the `generateURLsFromRoute` the sitemap generated successfully.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://ezwebproductions.com</loc>
    <lastmod>2023-05-27T00:20:18.419Z</lastmod>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://ezwebproductions.com/policies/privacy-policy</loc>
    <lastmod>2023-05-27T00:20:18.419Z</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://ezwebproductions.com/policies/terms-of-service</loc>
    <lastmod>2023-05-27T00:20:18.419Z</lastmod>
    <priority>0.8</priority>
  </url>
</urlset>
```

**Comment by steven87vt** [comment]
Created PR #31
